production:
  adapter: postgresql
  encoding: unicode
  database: sponge
  pool: 5
  username: root
  password:	romeinen

development:
  adapter: postgresql
  encoding: unicode
  database: sponge
  pool: 5
  username: root
  password: romeinen

test:
  adapter: postgresql
  encoding: unicode
  database: sponge
  pool: 5
  username: root
  password: romeinen