# Feel free to use this DB...be nice to it!
development:
  adapter: postgresql
  encoding: unicode
  database: d8pdk2ch4m782p
  pool: 5
  username: ozpmdlsvrcxvpt
  password: PGUrd0Yxj3ipqXEzAQoHmcBV38
  host: ec2-54-235-99-46.compute-1.amazonaws.com
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: sponge
  pool: 5
  username: sponge
  password: sponge_dev